### ISSUE TITLE
ページヘッダーとパンくずリストの非表示設定がないのは仕様ですか？

### ISSUE THREAD

**Issue by kaorock72** [vektor-inc/lightning-g3#1]
以前のようなページ毎のページヘッダーとパンくずリストの非表示設定が見当たらなかったのですが
これは仕様でしょうか？ページヘッダーとパンくずリストを非表示できるなら
ランディングページサンプルも入れたいです。

**Comment by kurudrive** [comment]
仕様デス ＞＜
プロ版のみになります。

**Comment by kaorock72** [comment]
了解です！ありがとうございます
